apiVersion: v1
kind: Secret
metadata:
  name: {{ include "security-sample-chart.fullname" . }}-database
  labels:
    {{- include "security-sample-chart.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-db: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  postgresql-user: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  postgresql-password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
